### ISSUE TITLE
doesn't  tensorrt3 support direct loading and transform tensorflow model?

### ISSUE THREAD

**Issue by ouceduxzk** [BoyDun/tensorflow-tensorrt#2]
Hi, I am following this nvidia blog post https://devblogs.nvidia.com/tensorrt-3-faster-tensorflow-inference/, but I did not get the result i want, is this the reason that you creaet this repo to load tensorflow model like this and create tensorrt model manually?

**Comment by bo-dun** [comment]
Yes -- You can use this converter to manually verify your intermediate layer outputs in TensorRT.

**Comment by ouceduxzk** [comment]
Thanks, I already verified that results with tf and tr is consistent in python api without using this framework

**Comment by bo-dun** [comment]
The converter was also primarily designed for tensorRT 2.0
